model:
  actor:
    layers:
      - dense:
          units: 64
          activation: relu
          input_shape: [2]
      - dense:
          units: 64
          activation: relu
      - dense:
          units: 1
          activation: tanh  # Output action in range [-1, 1]

  critic:
    layers:
      - dense:
          units: 64
          activation: relu
          input_shape: [2]  # state
    action_layers:
      - dense:
          units: 64
          activation: relu
          input_shape: [1]  # action
    post_concatenate_layers:
      - dense:
          units: 64
          activation: relu

training:
  optimizer_actor: adam
  optimizer_critic: rmsprop
  loss: mse
  metrics: [mae]
  num_episodes: 300
  learning_rate_actor: 0.001
  learning_rate_critic: 0.001
  buffer_size: 100000
  batch_size: 128
  gamma: 0.99
  tau: 0.01
  seed: 723
  beta_start: 0.4
  beta_increment: 1e-5
  action_size: 1
  callbacks:
    checkpoint:
      enabled: false
      filepath: checkpoints/mountain_car_actor.h5
      save_best_only: true
      monitor: val_loss
      save_weights_only: true
      verbose: 1
    early_stopping:
      enabled: false
      patience: 50
      monitor: val_loss
      restore_best_weights: true
    tensorboard:
      enabled: false
      log_dir: logs/training
      histogram_freq: 1
      update_freq: epoch
    lr_scheduler:
      enabled: true
      lr: 0.001
      lr_step_size: 1
      lr_decay_rate: 0.995
      type: exponential
  render:
    enabled: true
    frequency: 10

data:
  normalize: true
  dataset: mountain_car_continuous
  input_shape: 2
  batch_size: 128
  shuffle: true
  seed: 42
  buffer_size: 100000
  state_min: [-1.2, -0.07]
  state_max: [0.6, 0.07]
  prefetch: true

testing:
  num_episodes: 200
  max_steps: 200
  loss: mse
  metrics: [mae]
  epochs: 50
  validation_split: 0.2
  callbacks:
    checkpoint:
      enabled: true
    early_stopping:
      enabled: true
      patience: 20
      monitor: val_loss
      restore_best_weights: true
    tensorboard:
      enabled: true
      log_dir: logs/testing
    regularization:
      enabled: true
      l1: 0.0001
      l2: 0.0001
    lr_scheduler:
      enabled: true
      lr: 0.0005
      lr_step_size: 1
      lr_decay_rate: 0.995
      type: exponential
  gamma: 0.99